# KafkaProducer configurations
producer_config:
  topic_name: website_metrics
  host: localhost
  ssl_port: 9092
  security_protocol: SSL
  ssl_cafile: ./src/certifications/ca.pem
  ssl_certfile: ./src/certifications/service.cert
  ssl_keyfile: ./src/certifications/service.key

# KafkaCondumer configurations
consumer_config:
  topic_name: website_metrics
  host: localhost
  ssl_port: 9092
  consumer_timeout_ms: 10000
  client_id: CONSUMER_CLIENT_ID
  group_id: CONSUMER_GROUP_ID
  security_protocol: SSL
  ssl_cafile: ./src/certifications/ca.pem
  ssl_certfile: ./src/certifications/service.cert
  ssl_keyfile: ./src/certifications/service.key
  auto_offset_reset: earliest

# Database configurations
database_config:
  database_type: postgres
  user: avnadmin
  password: AVNS_F6meBmFcjsUq3VAbZQI
  host: localhost
  port: 9092
  database_name: defaultdb
  sslmode: sslmode=require

# List of websites to check
target_websites:  [
    'http://youtube.com',
    'http://google.com',
    'http://yahoo.fr'
]
